### ISSUE TITLE
List new skipped test cases

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#128]
### 🐛 Describe the bug

- [x]  test_noncontiguous_samples_native_dropout_backward_xpu_int64: CUDA fails with same error, IPEX has no such case, will skip. (RuntimeError: "masked_scale" not implemented for 'Long')
- [x] test_non_standard_bool_values_native_dropout_backward_xpu_bool: CUDA fails with same error, IPEX has no such case, will skip. (RuntimeError: "masked_scale" not implemented for 'Bool')
- [x] test_compare_cpu_nn_functional_alpha_dropout_xpu_float32: CUDA xfail, IPEX skips it, will skip.
- [x] test_dtypes_native_dropout_backward_xpu: Porting difference between IPEX and torch-xpu-ops, will skip ("masked_scale" does not claim int support)
- [ ] test_dtypes_nn_functional_linear_xpu: https://github.com/intel/torch-xpu-ops/issues/157
- [ ] test_dtypes_nn_functional_multi_head_attention_forward_xpu: https://github.com/intel/torch-xpu-ops/issues/157
- [ ] test_dtypes_pca_lowrank_xpu: https://github.com/intel/torch-xpu-ops/issues/157
- [ ] test_dtypes_svd_lowrank_xpu: https://github.com/intel/torch-xpu-ops/issues/157
- [ ] test_noncontiguous_samples_nn_functional_linear_xpu_int64: https://github.com/intel/torch-xpu-ops/issues/157
- [ ] 285 failures due to https://github.com/intel/torch-xpu-ops/issues/157

### Versions

Latest main

**Comment by daisyden** [comment]
move oneDNN issue to #253
