### ISSUE TITLE
Polygamma: UT failure

### ISSUE THREAD

**Issue by fengyuan14** [intel/torch-xpu-ops#622]
Triage is done
- [x] test_reference_numerics_normal_polygamma_polygamma_n_1_xpu_float16: cpu issue https://github.com/pytorch/pytorch/issues/132386
- [x] test_reference_numerics_normal_polygamma_polygamma_n_2_xpu_float16: cpu issue https://github.com/pytorch/pytorch/issues/132386
- [x] test_reference_numerics_normal_polygamma_polygamma_n_3_xpu_float16: cpu issue https://github.com/pytorch/pytorch/issues/132386
- [x] test_reference_numerics_normal_polygamma_polygamma_n_4_xpu_float16: cpu issue https://github.com/pytorch/pytorch/issues/132386

### 🐛 Describe the bug

Please evaluate `inf` in the error log, whether it is caused by numerical error when calculating a extremal large number. 4 failures,
```
=========================== short test summary info ============================
FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_normal_polygamma_polygamma_n_1_xpu_float16 - AssertionError: Tensor-likes are not close!

Mismatched elements: 8 / 943593 (0.0%)
Greatest absolute difference: inf at index (9, 860) (up to 0.001 allowed)
Greatest relative difference: inf at index (9, 860) (up to 0.0012 allowed)

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python test/test_unary_ufuncs.py -k TestUnaryUfuncsXPU.test_reference_numerics_normal_polygamma_polygamma_n_1_xpu_float16

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_normal_polygamma_polygamma_n_2_xpu_float16 - AssertionError: Tensor-likes are not close!

Mismatched elements: 8 / 943593 (0.0%)
Greatest absolute difference: inf at index (9, 860) (up to 0.001 allowed)
Greatest relative difference: inf at index (9, 860) (up to 0.0012 allowed)

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python test/test_unary_ufuncs.py -k TestUnaryUfuncsXPU.test_reference_numerics_normal_polygamma_polygamma_n_2_xpu_float16

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_normal_polygamma_polygamma_n_3_xpu_float16 - AssertionError: Tensor-likes are not close!

Mismatched elements: 8 / 943593 (0.0%)
Greatest absolute difference: inf at index (9, 860) (up to 0.001 allowed)
Greatest relative difference: inf at index (9, 860) (up to 0.0012 allowed)

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python test/test_unary_ufuncs.py -k TestUnaryUfuncsXPU.test_reference_numerics_normal_polygamma_polygamma_n_3_xpu_float16

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_normal_polygamma_polygamma_n_4_xpu_float16 - AssertionError: Tensor-likes are not close!

Mismatched elements: 8 / 943593 (0.0%)
Greatest absolute difference: inf at index (9, 860) (up to 0.001 allowed)
Greatest relative difference: inf at index (9, 860) (up to 0.0012 allowed)

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_SLOW=1 python test/test_unary_ufuncs.py -k TestUnaryUfuncsXPU.test_reference_numerics_normal_polygamma_polygamma_n_4_xpu_float16

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
= 4 failed, 15584 passed, 552 skipped, 2299 deselected, 16 xfailed in 131.29s (0:02:11) =
```

### Versions

https://github.com/intel/torch-xpu-ops/pull/555

**Comment by daisyden** [comment]
This op fallback to cpu, while cpu float16 range has gap with scipy. CPU issue is submitted https://github.com/pytorch/pytorch/issues/132386 with example code.

**Comment by daisyden** [comment]
duplicated with #745

**Comment by daisyden** [comment]
@yuchengliu1  please adjust tolerance for this case.

**Comment by daisyden** [comment]
tracked in #754
