### ISSUE TITLE
[MTL][Windows][UT] PT 2.5

### ISSUE THREAD

**Issue by min-jean-cho** [intel/torch-xpu-ops#666]
### 🐛 Describe the bug

1. **XPU OP Examples**
57 passed in 58.84s

2. **XPU OP Extended UT**
4 failed, 1233 passed, 309 skipped, 128 deselected, 14 xfailed in 186.95s (0:03:06)
- [x] FAILED test_ops_xpu.py::TestCommonXPU::test_compare_cpu_all_xpu_complex128 - ... https://github.com/intel/torch-xpu-ops/issues/663
- [ ] FAILED test_ops_xpu.py::TestCommonXPU::test_compare_cpu_pow_xpu_bfloat16 - As...
- [x] FAILED test_ops_xpu.py::TestCommonXPU::test_compare_cpu_sub_xpu_float16 - Ass... https://github.com/intel/torch-xpu-ops/issues/549
- [ ] FAILED test_ops_xpu.py::TestCompositeComplianceXPU::test_backward_nn_functional_embedding_bag_xpu_float32
Should be resolved with rebase or set PYTORCH_ENABLE_XPU_FALLBACK=1.

3.1 **XPU OP UT: run_test_with_only.py**
test_foreach_xpu.py: 437 passed, 40 skipped, 2986 deselected in 858.13s
test_decomp_xpu.py: 12 passed, 8760 deselected in 115.86s (0:01:55)

3.2. **XPU OP UT: run_test_with_skip.py** 
test_binary_ufuncs_xpu.py: 1 failed, 11713 passed, 794 skipped, 306 deselected, 28 xfailed in 294.64s (0:04:54)
test_scatter_gather_ops_xpu.py: 64 passed, 7 skipped, 2 deselected in 104.24s (0:01:44)
test_autograd_fallback.py: 28 passed in 2.69s 
test_transformers_xpu.py: 62 passed, 343 skipped, 47 deselected in 10.50s
test_complex_xpu.py: 11 passed, 4 deselected in 2.97s
test_nn_xpu.py: 997 failed, 652 passed, 482 skipped, 43 deselected, 3 xfailed in 89.93s (0:01:29)
test_sort_and_select_xpu.py: 91 passed, 7 skipped, 10 deselected in 13.96s
nn\test_embedding_xpu.py: 71 passed, 56 deselected in 5.37s
nn\test_pooling_xpu.py: 100 passed, 16 skipped, 9 deselected in 39.94s
nn\test_dropout_xpu.py: 7 passed, 2 deselected in 3.94s
test_indexing_xpu.py: 1 failed, 81 passed, 7 deselected in 5.42s
test_tensor_creation_ops_xpu: 23 failed, 446 passed, 142 skipped, 9 deselected in 1157.33s (0:19:17)
test_autocast_xpu.py: 4 passed, 1 deselected in 3.04s
test_autograd_xpu.py: 1 failed, 468 passed, 2 skipped, 23 deselected, 1 xfailed in 19.76s
test_reductions_xpu.py: 5 failed, 4248 passed, 153 skipped, 136 deselected, 61 xfailed in 128.33s (0:02:08)
test_unary_ufuncs_xpu.py: 41 failed, 19739 passed, 543 skipped, 2750 deselected, 4 xfailed in 730.21s (0:12:10)
test_masked_xpu.py: 50 passed, 58 skipped, 104 deselected in 23.76s
test_view_ops_xpu.py: 306 passed, 133 skipped, 2 deselected in 28.92s
test_shape_ops_xpu.py: 87 passed, 4 skipped, 2 deselected in 5.17s
test_content_store_xpu.py: 4 skipped in 2.67s
test_native_functions_xpu.py: 11 passed in 2.59s
nn\test_init_xpu.py: 21 passed, 9 skipped in 2.87s
test_namedtensor_xpu.py:  86 passed, 2 skipped in 2.86s
nn\test_packed_sequence_xpu.py: 9 passed, 3 deselected in 2.68s
nn\test_multihead_attention_xpu.py: 8 passed, 4 skipped, 7 deselected in 6.26s
nn\test_lazy_modules_xpu.py: 58 passed in 3.01s
test_matmul_cuda_xpu.py: 1 error in 2.72s
nn\test_packed_sequence_xpu.py: 9 passed, 3 deselected in 2.68s
test_comparison_utils_xpu.py: 5 passed in 2.61s

- [ ] FAILED test_binary_ufuncs_xpu.py::TestBinaryUfuncsXPU::test_pow_xpu_float16 AssertionError: Tensor-likes are not close!
- [ ] FAILED test_indexing_xpu.py::TestIndexingXPU::test_index_put_accumulate_large_tensor_xpu RuntimeError: XPU out of memory, please use `empty_cache` to release all unoccupied cached memory.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestTensorCreationXPU::test_float_to_int_conversion_finite_xpu_int64 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_alias_from_dlpack_xpu_bfloat16 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_alias_from_dlpack_xpu_complex128 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_alias_from_dlpack_xpu_complex64 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_alias_from_dlpack_xpu_float16 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_alias_from_dlpack_xpu_float32 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_alias_from_dlpack_xpu_float64 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_alias_from_dlpack_xpu_int16 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_alias_from_dlpack_xpu_int32 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_alias_from_dlpack_xpu_int64 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_alias_from_dlpack_xpu_int8 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_alias_from_dlpack_xpu_uint8 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_copy_from_dlpack_xpu_bfloat16 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_copy_from_dlpack_xpu_complex128 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_copy_from_dlpack_xpu_complex64 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_copy_from_dlpack_xpu_float16 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_copy_from_dlpack_xpu_float32 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_copy_from_dlpack_xpu_float64 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_copy_from_dlpack_xpu_int16 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_copy_from_dlpack_xpu_int32 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_copy_from_dlpack_xpu_int64 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_copy_from_dlpack_xpu_int8 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_tensor_creation_ops_xpu.py::TestAsArrayXPU::test_copy_from_dlpack_xpu_uint8 RuntimeError: Default context is not supported on XPU on Windows. So we can NOT find its global index of the ATen device.
- [ ] FAILED test_autograd_xpu.py::TestAutograd::test_multi_grad_all_hooks - Runtim... RuntimeError: Ninja is required to load C++ extensions
- [x] FAILED test_reductions_xpu.py::TestReductionsXPU::test_all_any_vs_numpy_xpu_complex128 AssertionError: Tensor-likes are not equal! https://github.com/intel/torch-xpu-ops/issues/663
- [x] FAILED test_reductions_xpu.py::TestReductionsXPU::test_all_any_vs_numpy_xpu_complex64 AssertionError: Tensor-likes are not equal! https://github.com/intel/torch-xpu-ops/issues/663
- [x] FAILED test_reductions_xpu.py::TestReductionsXPU::test_all_any_vs_numpy_xpu_float64 AssertionError: Tensor-likes are not equal! https://github.com/intel/torch-xpu-ops/issues/663
- [x] FAILED test_reductions_xpu.py::TestReductionsXPU::test_min_xpu_bool - Asserti... AssertionError: Tensor-likes are not equal! https://github.com/intel/torch-xpu-ops/issues/663
- [x] FAILED test_reductions_xpu.py::TestReductionsXPU::test_ref_duplicate_values_all_xpu_complex128 AssertionError: Tensor-likes are not equal! https://github.com/intel/torch-xpu-ops/issues/663
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal__refs_atanh_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal__refs_atanh_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal__refs_nn_functional_tanhshrink_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal__refs_sin_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal__refs_sin_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal__refs_sinh_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal__refs_sinh_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal__refs_tan_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal__refs_tan_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal_atanh_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal_atanh_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal_nn_functional_tanhshrink_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal_sin_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal_sin_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal_sinh_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal_sinh_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal_square_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal_square_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal_tan_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_extremal_tan_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_cos_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_cos_xpu_complex32
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_cos_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_cosh_xpu_complex32
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_exp_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_exp_xpu_complex32
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_exp_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_sin_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_sin_xpu_complex32
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_sin_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_sinh_xpu_complex32
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large__refs_tan_xpu_complex32
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large_cos_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large_cos_xpu_complex32
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large_cos_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large_exp_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large_exp_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large_sin_xpu_complex128
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large_sin_xpu_complex32
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_large_sin_xpu_complex64
- [ ] FAILED test_unary_ufuncs_xpu.py::TestUnaryUfuncsXPU::test_reference_numerics_small_acos_xpu_complex32
- [ ] ERROR test_matmul_cuda_xpu.py The command line is too long.
- [ ] FAILED test_nn_xpu.py::TestNNDeviceTypeXPU::test_grid_sample_bfloat16_precision_xpu - AssertionError: Torch not compiled with CUDA enabled
- [ ] FAILED test_nn_xpu.py::TestNNDeviceTypeXPU::test_grid_sample_half_precision_xpu - AssertionError: Torch not compiled with CUDA enabled
- [ ] FAILED test_nn_xpu.py::TestNNDeviceTypeXPU::test_grid_sample_large_xpu - RuntimeError: Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)

### Versions
- pytorch: c8626a4e1f0553c8a9af32515555409d151a00c0
- torch-xpu-ops: 47cbc58452e74f70afb5e7f108ff8d7ecc329f21
- [ ] Rebase to e1e195bd4d6f9541fc05c54579242f07f30a63b3 https://github.com/pytorch/pytorch/blob/main/third_party/xpu.txt
- oneAPI: w_intel-for-pytorch-gpu-dev_p_0.5.3.32
- OS: Windows 11
- Hardware: MTL
- AOT: xe-lpg
- Driver: 32.0.101.5764
- VS Studio Build Tools: 17.10.5

**Comment by chuanqi129** [comment]
@mengfei25 comments MTL linux UT test results. @daisyden double check the UT results

**Comment by mengfei25** [comment]
New test results on MTL. 40 failures
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_cuda_broadcast_index_use_deterministic_algorithms_xpu
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_index_put_accumulate_duplicate_indices_xpu
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_index_put_accumulate_expanded_values_xpu
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_index_put_accumulate_large_tensor_xpu
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_index_put_accumulate_non_contiguous_xpu
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_index_put_src_datatype_xpu_bfloat16
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_index_put_src_datatype_xpu_bool
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_index_put_src_datatype_xpu_complex128
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_index_put_src_datatype_xpu_complex64
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_index_put_src_datatype_xpu_float16
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_index_put_src_datatype_xpu_int64
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_take_along_dim_invalid_xpu_int64
PYTORCH_TEST_WITH_SLOW=1 python test/test_indexing.py -k TestIndexingXPU.test_take_along_dim_xpu_int64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_grad_nn_ConvTranspose1d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_grad_nn_ConvTranspose2d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_grad_nn_ConvTranspose3d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_grad_nn_LazyConvTranspose1d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_grad_nn_LazyConvTranspose2d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_grad_nn_LazyConvTranspose3d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_gradgrad_nn_Conv1d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_gradgrad_nn_Conv2d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_gradgrad_nn_Conv3d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_gradgrad_nn_LazyConv1d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_gradgrad_nn_LazyConv2d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_gradgrad_nn_LazyConv3d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_nn.py -k TestNNDeviceTypeXPU.test_grid_sample_large_xpu
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestCommonXPU.test_numpy_ref_nn_functional_conv_transpose1d_xpu_complex128
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestCommonXPU.test_numpy_ref_nn_functional_conv_transpose1d_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestCommonXPU.test_python_ref__refs_all_xpu_complex128
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestCommonXPU.test_python_ref__refs_nn_functional_group_norm_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestCommonXPU.test_python_ref_executor__refs_all_executor_aten_xpu_complex128
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestCommonXPU.test_python_ref_executor__refs_nn_functional_group_norm_executor_aten_xpu_float64
PYTORCH_TEST_WITH_SLOW=1 python test/test_ops.py -k TestCommonXPU.test_python_ref_torch_fallback__refs_all_xpu_complex128
PYTORCH_TEST_WITH_SLOW=1 python test/xpu/extended/test_ops_xpu.py -k TestCommonXPU.test_compare_cpu_all_xpu_complex128
PYTORCH_TEST_WITH_SLOW=1 python test/xpu/extended/test_ops_xpu.py -k TestCommonXPU.test_compare_cpu_argmin_xpu_int16
PYTORCH_TEST_WITH_SLOW=1 python test/xpu/extended/test_ops_xpu.py -k TestCommonXPU.test_compare_cpu_argmin_xpu_int32
PYTORCH_TEST_WITH_SLOW=1 python test/xpu/extended/test_ops_xpu.py -k TestCommonXPU.test_compare_cpu_argmin_xpu_int64
PYTORCH_TEST_WITH_SLOW=1 python test/xpu/extended/test_ops_xpu.py -k TestCommonXPU.test_compare_cpu_argmin_xpu_int8
PYTORCH_TEST_WITH_SLOW=1 python test/xpu/extended/test_ops_xpu.py -k TestCommonXPU.test_compare_cpu_argmin_xpu_uint8
PYTORCH_TEST_WITH_SLOW=1 python test/xpu/test_gemm.py -k TestBasicGEMMXPU.test_addmv_xpu_float16

**Comment by Stonepia** [comment]
Will update this once a new round test is done.
